[project]
name = "grg-spmv"
version = "0.1.0"
description = "GRG matvec/matmat with SpMV"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cupy-cuda12x>=13.6.0",
    "grapp>=0.2",
    "igdtools>=2.6",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pygrgl>=2.5",
    "pytest>=9.0.2",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
]

[tool.pytest.ini_options]
markers = [
    "gpu: tests requiring a GPU (CuPy + cuSPARSE)",
    "cpu: tests specific to CPU multithread backend",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"
pythonPlatform = "x86_64-unknown-linux-gnu"
